### ISSUE TITLE
提示无效的corpid

### ISSUE THREAD

**Issue by iamdominate** [DingGuodong/LinuxBashShellScriptForOps#1]
<class 'sqlite3.OperationalError'> : no such table: weixin_token
WeiXin_Qy Api Error, result is {u'errcode': 40013, u'errmsg': u'invalid corpid'}

**Comment by DingGuodong** [comment]
首先感谢你提出问题！根据你提供的错误信息，问题的原因可能是这样的：weixin_token 表没有正确设置，可能需要你去人工核查一下sqlite数据库中这个表是否存在，如果不存在可以尝试重新运行脚本初始化sqlite数据库。

**Comment by DingGuodong** [comment]
不要使用git上提供给你的sqlite数据库文件“.odbp_db.sqlite3”，你完全可以删除这个文件，然后按照README.md的使用方法去再试一次，应该没有问题。如果再次试过之后发现还是有问题，请再Open这个issue。
