### ISSUE TITLE
pyGetTCPPortStatisticsOnLocal.py not support on python2.6

### ISSUE THREAD

**Issue by tanjiangfu** [DingGuodong/LinuxBashShellScriptForOps#2]
LinuxBashShellScriptForOps/functions/net/tcp/port/pyGetTCPPortStatisticsOnLocal.py
pyGetTCPPortStatisticsOnLocal.py 
it not support on python2.6, 
Traceback (most recent call last):
  File "2.py", line 27, in <module>
    from collections import \
ImportError: cannot import name Counter
can you  fix it ? ths

**Comment by DingGuodong** [comment]
I'm sorry about it, Counter is **only supported python 2.7** and higher and is not available in earlier versions. 

**BUT**, if you have saw the source code of 'Counter', you should known it just depends 'dict' object, you can put the implementation in Python 2.7 into your own script.

Thanks.

Now. I close this issue.
